<a href="https://colab.research.google.com/github/cpoorna050-dot/AI_ML-Lessons/blob/main/Lesson8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# Python list
python_list = [1, 2, 3, 4, 5]
print("Python list:", python_list)
print("Type:", type(python_list))



# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print("NumPy array:", numpy_array)
print("Type:", type(numpy_array))


Python list: [1, 2, 3, 4, 5]
Type: <class 'list'>
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [ ]:

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)


# Array of ones
ones = np.ones(5)
print("Ones:", ones)


# Range of numbers
range_arr = np.arange(0, 10, 2)  # Start, stop, step
print("Range:", range_arr)


# Evenly spaced numbers
spaced = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1
print("Spaced:", spaced)


Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Range: [0 2 4 6 8]
Spaced: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 2D array (matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)  # (rows, columns)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


In [ ]:
image = np.array([[0, 128, 255],
                 [64, 128, 192],
                 [255, 128, 0]])
print("Tiny image:")
print(image)
print("Shape:", image.shape)  # 3 pixels tall, 3 pixels wide


Tiny image:
[[  0 128 255]
 [ 64 128 192]
 [255 128   0]]
Shape: (3, 3)


In [ ]:
numbers = [1, 2, 3, 4, 5]
result = []
for num in numbers:
   result.append(num + 10)
print("Loop result:", result)


Loop result: [11, 12, 13, 14, 15]


In [ ]:
# NumPy - fast way
numbers = np.array([1, 2, 3, 4, 5])
result = numbers + 10
print("NumPy result:", result)

NumPy result: [11 12 13 14 15]


In [ ]:

arr = np.array([1, 2, 3, 4, 5])

print("Original:", arr)
print("Add 10:", arr + 10)
print("Multiply by 2:", arr * 2)
print("Square:", arr ** 2)
print("Divide by 2:", arr / 2)


Original: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])


print("Array 1:", arr1)
print("Array 2:", arr2)
print("Add arrays:", arr1 + arr2)
print("Multiply arrays:", arr1 * arr2)
print("Divide arrays:", arr1 / arr2)


Array 1: [10 20 30 40 50]
Array 2: [1 2 3 4]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D array:", arr_1d)
print("Shape:", arr_1d.shape)  # (6,) means 6 elements


1D array: [1 2 3 4 5 6]
Shape: (6,)


In [ ]:
# 2D array
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("\n2D array:")
print(arr_2d)
print("Shape:", arr_2d.shape)  # (2, 3) means 2 rows, 3 columns



2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [ ]:
# 3D array
arr_3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print("\n3D array:")
print(arr_3d)
print("Shape:", arr_3d.shape)  # (2, 2, 2)



3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [ ]:

# Start with 12 numbers
arr = np.arange(12)
print("Original (12 numbers):", arr)
print("Shape:", arr.shape)


Original (12 numbers): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)


In [ ]:
# Reshape to 3 rows × 4 columns
reshaped_3x4 = arr.reshape(3, 4)
print("\nReshaped to 3×4:")
print(reshaped_3x4)
print("Shape:", reshaped_3x4.shape)


Reshaped to 3×4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)


In [ ]:
# Reshape to 4 rows × 3 columns
reshaped_4x3 = arr.reshape(4, 3)
print("\nReshaped to 4×3:")
print(reshaped_4x3)
print("Shape:", reshaped_4x3.shape)



Reshaped to 4×3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)


In [ ]:
# Reshape to 2×2×3
reshaped_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2×2×3:")
print(reshaped_3d)


Reshaped to 2×2×3:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:

# Image data often comes as flat array
flat_image = np.arange(9)  # 9 pixels
print("Flat pixels:", flat_image)


# Reshape to 3×3 image
image = flat_image.reshape(3, 3)
print("\nAs image (3×3):")
print(image)


# Flatten back
flattened = image.reshape(-1)  # -1 = auto-calculate
print("\nFlattened:", flattened)


Flat pixels: [0 1 2 3 4 5 6 7 8]

As image (3×3):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Flattened: [0 1 2 3 4 5 6 7 8]


In [ ]:
import time

# Create large dataset
size = 1000000  # 1 million numbers

# Python list approach
python_list = list(range(size))
start = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start
print(f"Python list time: {python_time:.4f} seconds")


# NumPy approach
numpy_array = np.arange(size)
start = time.time()
result_numpy = numpy_array * 2
numpy_time = time.time() - start
print(f"NumPy time: {numpy_time:.4f} seconds")


# Calculate speedup
speedup = python_time / numpy_time
print(f"\nNumPy is {speedup:.0f}x faster!")


Python list time: 0.0765 seconds
NumPy time: 0.0035 seconds

NumPy is 22x faster!


In [ ]:
import sys

# Python list
python_list = list(range(1000))
list_size = sys.getsizeof(python_list)
print(f"Python list size: {list_size} bytes")


# NumPy array
numpy_array = np.arange(1000)
array_size = numpy_array.nbytes
print(f"NumPy array size: {array_size} bytes")


print(f"\nNumPy uses {list_size / array_size:.1f}x less memory")


Python list size: 8056 bytes
NumPy array size: 8000 bytes

NumPy uses 1.0x less memory


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])


# Basic indexing
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Third element:", arr[2])


# Slicing
print("First 3:", arr[:3])
print("Last 2:", arr[-2:])
print("Every other:", arr[::2])


First element: 10
Last element: 60
Third element: 30
First 3: [10 20 30]
Last 2: [50 60]
Every other: [10 30 50]


In [ ]:
#2d
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print("Element at row 1, col 2:", matrix[1, 2])  # 6
print("First row:", matrix[0])
print("First column:", matrix[:, 0])
print("2×2 submatrix:")
print(matrix[:2, :2])


Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
2×2 submatrix:
[[1 2]
 [4 5]]


In [ ]:
scores = np.array([85, 92, 78, 95, 88, 73, 90])


# Find high scores
high_scores = scores > 85
print("Scores > 85?:", high_scores)
print("High scores:", scores[high_scores])


# Find specific range
mid_range = (scores >= 80) & (scores <= 90)
print("Scores 80-90:", scores[mid_range])


Scores > 85?: [False  True False  True  True False  True]
High scores: [92 95 88 90]
Scores 80-90: [85 88 90]


In [ ]:
data = np.array([23, 45, 67, 89, 34, 56, 78, 90, 12])


print("Data:", data)
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Std deviation:", np.std(data))
print("Median:", np.median(data))


Data: [23 45 67 89 34 56 78 90 12]
Sum: 494
Mean: 54.888888888888886
Min: 12
Max: 90
Std deviation: 26.80980104549016
Median: 56.0


In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


print("Total sum:", np.sum(matrix))
print("Sum each column:", np.sum(matrix, axis=0))
print("Sum each row:", np.sum(matrix, axis=1))


Total sum: 45
Sum each column: [12 15 18]
Sum each row: [ 6 15 24]


In [ ]:
def create_sample_image():
   """Create a tiny 5×5 grayscale image"""
   # Random values 0-255 (grayscale)
   np.random.seed(42)  # For consistent results
   image = np.random.randint(0, 256, size=(5, 5))
   return image


def adjust_brightness(image, amount):
   """Adjust brightness by adding/subtracting value"""
   adjusted = image + amount
   # Clip to valid range 0-255
   adjusted = np.clip(adjusted, 0, 255)
   return adjusted


def adjust_contrast(image, factor):
   """Adjust contrast by multiplying"""
   adjusted = image * factor
   adjusted = np.clip(adjusted, 0, 255)
   return adjusted


# Create image
image = create_sample_image()
print("Original Image:")
print(image)
print(f"Brightness range: {np.min(image)} to {np.max(image)}")


# Brighten
brightened = adjust_brightness(image, 50)
print("\nBrightened (+50):")
print(brightened)
print(f"New range: {np.min(brightened)} to {np.max(brightened)}")


# Darken
darkened = adjust_brightness(image, -30)
print("\nDarkened (-30):")
print(darkened)


# Increase contrast
high_contrast = adjust_contrast(image, 1.5)
print("\nHigh Contrast (×1.5):")
print(high_contrast.astype(int))


Original Image:
[[102 179  92  14 106]
 [ 71 188  20 102 121]
 [210 214  74 202  87]
 [116  99 103 151 130]
 [149  52   1  87 235]]
Brightness range: 1 to 235

Brightened (+50):
[[152 229 142  64 156]
 [121 238  70 152 171]
 [255 255 124 252 137]
 [166 149 153 201 180]
 [199 102  51 137 255]]
New range: 51 to 255

Darkened (-30):
[[ 72 149  62   0  76]
 [ 41 158   0  72  91]
 [180 184  44 172  57]
 [ 86  69  73 121 100]
 [119  22   0  57 205]]

High Contrast (×1.5):
[[153 255 138  21 159]
 [106 255  30 153 181]
 [255 255 111 255 130]
 [174 148 154 226 195]
 [223  78   1 130 255]]


In [ ]:
def create_grade_data():
   """Simulate scores for 30 students, 5 exams"""
   np.random.seed(100)
   # Scores between 60-100
   scores = np.random.randint(60, 101, size=(30, 5))
   return scores


def analyze_grades(scores):
   """Comprehensive grade analysis"""
   print("=== Grade Analysis ===")
   print(f"Total students: {scores.shape[0]}")
   print(f"Total exams: {scores.shape[1]}")

   # Overall statistics
   print(f"\nClass average: {np.mean(scores):.1f}")
   print(f"Highest score: {np.max(scores)}")
   print(f"Lowest score: {np.min(scores)}")
   print(f"Standard deviation: {np.std(scores):.1f}")

   # Per-exam analysis
   exam_averages = np.mean(scores, axis=0)
   print(f"\nExam averages:")
   for i, avg in enumerate(exam_averages, 1):
       print(f"  Exam {i}: {avg:.1f}")

   # Per-student analysis
   student_averages = np.mean(scores, axis=1)
   print(f"\nTop 5 students (by average):")
   top_indices = np.argsort(student_averages)[-5:][::-1]
   for rank, idx in enumerate(top_indices, 1):
       print(f"  {rank}. Student {idx+1}: {student_averages[idx]:.1f}")

   # Grade distribution
   a_students = np.sum(student_averages >= 90)
   b_students = np.sum((student_averages >= 80) & (student_averages < 90))
   c_students = np.sum((student_averages >= 70) & (student_averages < 80))

   print(f"\nGrade Distribution:")
   print(f"  A (90+): {a_students} students")
   print(f"  B (80-89): {b_students} students")
   print(f"  C (70-79): {c_students} students")

   # Students who need help
   struggling = student_averages < 70
   if np.any(struggling):
       print(f"\nStudents needing support: {np.sum(struggling)}")
       print(f"  IDs: {np.where(struggling)[0] + 1}")


# Run analysis
scores = create_grade_data()
print("Sample scores (first 5 students):")
print(scores[:5])
print()